### ISSUE TITLE
KidTrendingProducts

### ISSUE THREAD

**Issue by andriadze6** [andriadze6/Task-10#4]
1.სურათების და შესაბამის ინფორმაციის მოძიება 
2. დაემატოს ბავშვების პრდუქცია product Table_ში 
3.  ბავშების პრდუქციის წამღება და ფეიჯზე გამოტანა

**Comment by Iamyouandwhatiseeisme** [comment]
1.სურათების და შესაბამის ინფორმაციის მოძიება - Done.
2. დაემატოს ბავშვების პრდუქცია product Table_ში - Done.
3. KidTrending -ცხრილი, Foreign key საშუალებით დაუკავშირდეს product თეიბლს - Done
4. დაიწეროს View რომელიც გარდაიქმენა endpointad და წამოღებს მამაკიც ტრენდული ტანსაცმელს - ალბათ kids იგულისხმება.
5. დიზაინიდა გამომდინა გვჭირდება მხოლოდ პრდუქის ID და სურათების

ვხსნი ბრენჩს რომ რეპოზიტორიაში შევქმნა kidsTrending ფეიჯი და API ენდფოინთის მეშვეობით წამოვიღო ბაზიდან ინფორმაცია.

**Comment by Iamyouandwhatiseeisme** [comment]
4. Done
5. Done
